# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'IpFinderUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import requests


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 30, 55, 16))
        self.label.setObjectName("label")
        self.inputArea = QtWidgets.QLineEdit(self.centralwidget)
        self.inputArea.setGeometry(QtCore.QRect(60, 50, 371, 31))
        self.inputArea.setObjectName("inputArea")
        self.FindBTN = QtWidgets.QPushButton(self.centralwidget)
        self.FindBTN.setGeometry(QtCore.QRect(460, 50, 91, 31))
        self.FindBTN.setObjectName("FindBTN")
        self.FindBTN.clicked.connect(self.getIP)  #getIp is function name
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(20, 120, 751, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 150, 55, 16))
        self.label_2.setObjectName("label_2")
        self.ResultArea = QtWidgets.QTextBrowser(self.centralwidget)
        self.ResultArea.setGeometry(QtCore.QRect(60, 180, 481, 351))
        self.ResultArea.setObjectName("ResultArea")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    #make function
    def getIP(self):
        #take input text from input field
        ipp = str(self.inputArea.text())
        #here is API url
        linkURl = "https://api.techniknews.net/ipgeo/"
        try:
            respond = requests.get(linkURl+ipp).json()
            ip = respond['ip']
            status = respond['status']
            continent = respond['continent']
            country = respond['country']
            countryCode = respond['countryCode']
            regionName = respond['regionName']
            city = respond['city']
            zip = respond['zip']
            lat = respond['lat']
            lon = respond['lon']
            timezone = respond['timezone']
            currency = respond['currency']
            isp = respond['isp']
            org = respond['org']
            mobile = respond['mobile']
            proxy = respond['proxy']

            finalResult = f'IP : {ip}\nStatus : {status}\nContinent : {continent}\nCountry : {country}\nCountryCode : {countryCode}\nRegionName : {regionName}\nCity : {city}\nZip : {zip}\nLat : {lat}\nLon : {lon}\nTimezone : {timezone}\nCurrency : {currency}\nIsp : {isp}\nOrg : {org}\nMobile : {mobile}\nProxy : {proxy}\n\n'

            # now set the result in result area
            self.ResultArea.setText(finalResult)
        except:
            finalResult = "Not found . Try another IP"    
            self.ResultArea.setText(finalResult)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Enter IP"))
        self.FindBTN.setText(_translate("MainWindow", "Find"))
        self.label_2.setText(_translate("MainWindow", "Details"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
